apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-a
  template:
    metadata:
      labels:
        app: pod-a
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pod-a
            topologyKey: "kubernetes.io/hostname"
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 60
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-a
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: container-a-nginx
        image: nginx
        ports:
        - containerPort: 80
